[package]
name = "nphysics-ecs-dumb"
version = "0.1.0"
authors = ["kel <distransient@protonmail.com>"]
edition = "2018"

#[features]
# default = [ "nphysics3d" ]

[dependencies]
nphysics3d = "0.9"
ncollide3d = "0.17"
nalgebra = "0.16"
num-traits = "0.2"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
branch = "master"
features = ["nightly"]
